# Rakeを利用するためのRakefile（タスクの定義はload_tasksを呼びだした際に行われる）(12.7)
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks
